import { Resguardante } from '@/src/models/types';

export const dataResguardantes: Resguardante[] = [
  {
    res_nombre: 'Juan',
    res_apellidos: 'Perez Gonzalez',
    res_puesto: 'Gestor',
    res_correo: 'jperez@empresa.com',
    res_telefono: '+52 123 456 7890',
    res_departamento: 'Sistemas',
    res_id_usuario: '1',
    res_rfc: 'PEGJ800101ABC',
    res_curp: 'PEGJ800101HDFRRC01',
    id_oficina: 'Oficina Central',
  },
  {
    res_nombre: 'Ana',
    res_apellidos: 'Pech Hernandez',
    res_puesto: 'Resguardante',
    res_correo: 'apech@empresa.com',
    res_telefono: '+52 234 567 8901',
    res_departamento: 'Recursos Humanos',
    res_id_usuario: '2',
    res_rfc: 'PEHA750505DEF',
    res_curp: 'PEHA750505MDFPRR02',
    id_oficina: 'Oficina Norte',
  },
  {
    res_nombre: 'Carlos',
    res_apellidos: 'Lopez Martinez',
    res_puesto: 'Resguardante',
    res_correo: 'clopez@empresa.com',
    res_telefono: '+52 345 678 9012',
    res_departamento: 'Contabilidad',
    res_id_usuario: '3',
    res_rfc: 'LOMC820202GHI',
    res_curp: 'LOMC820202HDFDVL03',
    id_oficina: 'Oficina Central',
  },
  {
    res_nombre: 'Maria',
    res_apellidos: 'Garcia Rodriguez',
    res_puesto: 'Resguardante',
    res_correo: 'mgarcia@empresa.com',
    res_telefono: '+52 456 789 0123',
    res_departamento: 'Finanzas',
    res_id_usuario: '4',
    res_rfc: 'GARM780606JKL',
    res_curp: 'GARM780606MDFMTL04',
    id_oficina: 'Oficina Sur',
  },
  {
    res_nombre: 'Farid',
    res_apellidos: 'Djamel Alvarez',
    res_puesto: 'Resguardante',
    res_correo: 'fdjamel@empresa.com',
    res_telefono: '+52 567 890 1234',
    res_departamento: 'Innovación',
    res_id_usuario: '5',
    res_rfc: 'DJAF871212MNO',
    res_curp: 'DJAF871212HDFRTR05',
    id_oficina: 'Oficina Central',
  },
  {
    res_nombre: 'Hector',
    res_apellidos: 'Cruz Santos',
    res_puesto: 'Resguardante',
    res_correo: 'hcruz@empresa.com',
    res_telefono: '+52 678 901 2345',
    res_departamento: 'Sistemas',
    res_id_usuario: '6',
    res_rfc: 'CRSH890808PQR',
    res_curp: 'CRSH890808HDFRRC06',
    id_oficina: 'Oficina Norte',
  },
  {
    res_nombre: 'Alejandro',
    res_apellidos: 'Poot Castro',
    res_puesto: 'Resguardante',
    res_correo: 'apoot@empresa.com',
    res_telefono: '+52 789 012 3456',
    res_departamento: 'Recursos Humanos',
    res_id_usuario: '7',
    res_rfc: 'POCA900303STU',
    res_curp: 'POCA900303MDFSJF07',
    id_oficina: 'Oficina Sur',
  },
  {
    res_nombre: 'Alejandro',
    res_apellidos: 'Pech Vargas',
    res_puesto: 'Resguardante',
    res_correo: 'apech2@empresa.com',
    res_telefono: '+52 890 123 4567',
    res_departamento: 'Contabilidad',
    res_id_usuario: '8',
    res_rfc: 'PEVA920202VWX',
    res_curp: 'PEVA920202HDFRRG08',
    id_oficina: 'Oficina Central',
  },
  {
    res_nombre: 'Ana',
    res_apellidos: 'Pech Morales',
    res_puesto: 'Resguardante',
    res_correo: 'apech3@empresa.com',
    res_telefono: '+52 901 234 5678',
    res_departamento: 'Finanzas',
    res_id_usuario: '9',
    res_rfc: 'PEMA850505YZA',
    res_curp: 'PEMA850505MDFZNR09',
    id_oficina: 'Oficina Norte',
  },
  {
    res_nombre: 'Luis',
    res_apellidos: 'Sanchez Ruiz',
    res_puesto: 'Administrador',
    res_correo: 'lsanchez@empresa.com',
    res_telefono: '+52 012 345 6789',
    res_departamento: 'Innovación',
    res_id_usuario: '10',
    res_rfc: 'SARL940404BCD',
    res_curp: 'SARL940404HDFNRS10',
    id_oficina: 'Oficina Sur',
  },
];
